# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

  
steps:
- task: RegexReplace@3
  inputs:
    InputSearchPattern: '**\settings.py'
    FindRegex: '^(REDIS_URL =)'
    ReplaceRegex: '$(REDIS_URL)'
    UseUTF8: true
    UseRAW: true
  displayName: 'Run a one-line script'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      vim  $(System.DefaultWorkingDirectory)/Celine_Project/Celine/settings.py
