# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

  
steps:
- task: RegexReplace@3
  inputs:
    InputSearchPattern: '**\settings.py'
    FindRegex: $(FindRegex)
    ReplaceRegex: $(ReplaceRegex)
    UseUTF8: true
    UseRAW: true
  displayName: 'Run a one-line script'


- task: ArchiveFiles@2
  name: 'Archive_Celine_Project'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Celine_Project'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/Celine_Project.zip'
    replaceExistingArchive: true

- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/Celine_Project/Celine/settings.py'
    azureSubscription: 'XSHOUDAI-PROD(2fcfe293-fbb3-486f-ae7a-41111cfbc474)'
    Destination: 'AzureBlob'
    storage: 'xshoudaistorageuat'
    ContainerName: 'xshoudai-prod-pipeline'
    BlobPrefix: 'Celine_Project_settings.py'